title: My title
author: Patrick King
email: pking70@uw.edu
description: > # this means to ignore newlines until "baseurl:"
  This site is for learning github pages with Jekyll.

# social links
twitter_username: partking7
github_username:  pking70

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
